INSERT INTO times VALUES 
(1, 'São Paulo Futebol Clube', 'São Paulo', 'Morumbi'),
(2, 'Sociedade Esporte Palmeiras', 'São Paulo', 'Allianz Parque'),
(3, 'Sport Club Corinthians Paulista', 'São Paulo', 'Arena Corinthians'),
(4, 'Santos Futebol Clube', 'Santos', 'Vila Belmiro'),
(5, 'Esporte Clube XV de Novembro', 'Piracicaba', 'Barão de Serra Negra'),
(6, 'Associação Ferroviária de Esportes', 'Araraquara', 'Fonte Luminosa'),
(7, 'Ituano Futebol Clube', 'Itu', 'Novelli Júnior'),
(8, 'Clube Atlético Linense', 'Lins', 'Gilberto Siqueira Lopes'),
(9, 'Mogi Mirim Esporte Clube', 'Mogi Mirim', 'Vail Chaves'),
(10, 'Grêmio Novorizontino', 'Novo Horizonte', 'Jorge Ismael de Biasi'),
(11, 'Oeste Futebol Clube', 'Itápolis', 'Amaros'),
(12, 'Botafogo Futebol Clube', 'Ribeirão Preto', 'Santa Cruz'),
(13, 'Associação Atlética Ponte Preta', 'Campinas', 'Moisés Lucarelli'),
(14, 'Red Bull Brasil', 'Campinas', 'Moisés Lucarelli'),
(15, 'Rio Clario Futebol Clube', 'Rio Claro', 'Augusto Schmidt Filho'),
(16, 'Capivariano Futebol Clube', 'Capivari', 'Arena Capivari'),
(17, 'Esporte Clube São Bento', 'Sorocaba', 'Walter Ribeiro'),
(18, 'São Bernardo Futebol Clube', 'São Bernardo do Campo', 'Primeiro de Maio'),
(19, 'Grêmio Osasco Audax', 'Osasco', 'José Liberatti'),
(20, 'Esporte Clube Água Santa', 'Diadema', 'Distrital do Inamar')
