--ADICIONA SETE DIAS NA DATA DE HOJE
SELECT DATEADD(DAY, 7, GETDATE())

--CONVERTE PARA DD/MM/YYYY
SELECT CONVERT(CHAR, DATEADD(DAY, 7, GETDATE()), 103)

--RETORNA O NOME DO DIA DA SEMANA
 SELECT DATENAME(W, DATEADD(DAY, 4, GETDATE()))
 
 --ARREDONDA NUMERO ALEATORIO PARA BAIXO ATE 12 
 SELECT ROUND(RAND() * 12, 0, 1);

 SELECT * FROM v_grupos ORDER BY grupo

CREATE PROCEDURE sp_gerarRodadas(@CLUBE VARCHAR(100), @OUT VARCHAR(MAX) OUTPUT)
AS
	DECLARE @dataInicio DATETIME

	SET @dataInicio = '30/01/2019'

	PRINT @dataInicio

	SELECT DATENAME(W, '30/01/2019')

	SELECT DATENAME(W, DATEADD(DAY, 4, '30/01/2019'))

	DECLARE @grupoCasa CHAR(1),
			@grupoAdv CHAR(1),
			@adversario INT,
			@CLUBE VARCHAR(100)

	SET @CLUBE = 'Esporte Clube Água Santa'
	SET @grupoCasa = (SELECT grupo FROM v_grupos WHERE nomeTime = @CLUBE)
	PRINT @grupoCasa

	



