--ADICIONA SETE DIAS NA DATA DE HOJE
SELECT DATEADD(DAY, 7, GETDATE())

--CONVERTE PARA DD/MM/YYYY
SELECT CONVERT(CHAR, DATEADD(DAY, 7, GETDATE()), 103)

--RETORNA O NOME DO DIA DA SEMANA
 SELECT DATENAME(W, DATEADD(DAY, 4, GETDATE()))
 
 --ARREDONDA NUMERO ALEATORIO PARA BAIXO ATE 12 
 SELECT ROUND(RAND() * 12, 0, 1);

CREATE PROCEDURE sp_gerarRodadas(@OUT VARCHAR(MAX) OUTPUT)
AS



